terraform {
  required_version = ">= 1.0"
  
  required_providers {
    konnect = {
      source  = "kong/konnect"
      version = ">= 2.8.0"
    }
    konnect-beta = {
      source  = "kong/konnect-beta"
      version = ">= 0.4.1"
    }
    http = {
      source  = "hashicorp/http"
      version = ">= 3.0"
    }
  }
}

# Providers
provider "konnect" {
  personal_access_token = var.konnect_token
  server_url            = var.konnect_server_url
}

provider "konnect-beta" {
  personal_access_token = var.konnect_token
  server_url            = var.konnect_server_url
}

# Data sources to fetch existing resources
data "http" "control_planes" {
  url = "${var.konnect_server_url}/v2/control-planes"
  request_headers = {
    Accept        = "application/json"
    Authorization = "Bearer ${var.konnect_token}"
  }
}

data "http" "portals" {
  url = "${var.konnect_server_url}/v3/portals"
  request_headers = {
    Accept        = "application/json"
    Authorization = "Bearer ${var.konnect_token}"
  }
}

# Local values
locals {
  # Parse APIs configuration
  apis_config = yamldecode(file(var.apis_config_file))
  
  # Find the control plane and portal IDs
  control_planes = jsondecode(data.http.control_planes.response_body).data
  portals        = jsondecode(data.http.portals.response_body).data
  
  control_plane = [
    for cp in local.control_planes : cp
    if cp.name == var.control_plane_name
  ][0]
  
  portal = [
    for p in local.portals : p
    if p.name == var.portal_name
  ][0]
  
  control_plane_id = local.control_plane.id
  portal_id        = local.portal.id
  
  # Portal pages configuration
  portal_pages = var.enable_portal_pages ? try(local.apis_config.portal.pages, {}) : {}
}

# ===================================================================
# IMPORT DECK-GENERATED TERRAFORM RESOURCES

# Service mapping for API implementations
locals {
  deck_generated_services = {
    "rami-apiops-demo" = konnect_gateway_service.rami_apiops_demo.id
  }
}


# ===================================================================
# GATEWAY RESOURCES FOR: oas.yaml (rami-apiops-demo)
# Generated by deck from OpenAPI specification
# ===================================================================

resource "konnect_gateway_service" "rami_apiops_demo" {
  name = "rami-apiops-demo"
  connect_timeout = 60000
  host = "httpbin.org"
  path = "/"
  port = 443
  protocol = "https"
  read_timeout = 60000
  retries = 6
  tags = ["owner=rami", "created_by:terraform", "environment:dev"]
  write_timeout = 60000

  control_plane_id = local.control_plane_id
}

resource "konnect_gateway_route" "rami_apiops_demo_httpbin_anything" {
  name = "rami-apiops-demo_httpbin-anything"
  methods = ["GET"]
  paths = ["~/anything$"]
  regex_priority = 200
  strip_path = false
  tags = ["owner=rami", "created_by:terraform", "environment:dev"]

  service = {
    id = konnect_gateway_service.rami_apiops_demo.id
  }

  control_plane_id = local.control_plane_id
}

resource "konnect_gateway_route" "rami_apiops_demo_httpbin_post" {
  name = "rami-apiops-demo_httpbin-post"
  methods = ["POST"]
  paths = ["~/post$"]
  regex_priority = 200
  strip_path = false
  tags = ["owner=rami", "created_by:terraform", "environment:dev"]

  service = {
    id = konnect_gateway_service.rami_apiops_demo.id
  }

  control_plane_id = local.control_plane_id
}

resource "konnect_gateway_plugin_rate_limiting" "rami_apiops_demo_rate_limiting" {
  enabled = true
  config = {
    hide_client_headers = false
    hour = 1000
    minute = 90
    policy = "local"
  }
  tags = ["owner=rami", "created_by:terraform", "environment:dev"]

  service = {
    id = konnect_gateway_service.rami_apiops_demo.id
  }

  control_plane_id = local.control_plane_id
}

# PORTAL RESOURCES
# ===================================================================

# Portal Pages
resource "konnect_portal_page" "pages" {
  for_each = local.portal_pages
  
  provider    = konnect-beta
  portal_id   = local.portal_id
  title       = each.value.title
  slug        = each.value.slug
  description = try(each.value.description, "")
  visibility  = try(each.value.visibility, "public")
  status      = try(each.value.status, "published")
  content     = each.value.content
}

# Portal APIs
resource "konnect_api" "apis" {
  for_each = local.apis_config.apis
  
  provider    = konnect-beta
  name        = each.value.name
  description = each.value.description
  labels      = each.value.labels
  slug        = each.value.slug
  version     = each.value.version
}

# API Specifications
resource "konnect_api_specification" "specifications" {
  for_each = local.apis_config.apis
  
  provider = konnect-beta
  api_id   = konnect_api.apis[each.key].id
  content  = file("${var.specs_directory}/${each.value.spec_file}")
  type     = each.value.spec_type
}

# API Documents
resource "konnect_api_document" "documents" {
  for_each = local.apis_config.apis
  
  provider = konnect-beta
  api_id   = konnect_api.apis[each.key].id
  content  = each.value.documentation.content
  slug     = each.value.documentation.slug
  status   = each.value.documentation.status
  title    = each.value.documentation.title
}

# API Implementations (link APIs to deck-generated Gateway Services)
resource "konnect_api_implementation" "implementations" {
  for_each = local.apis_config.apis
  
  provider = konnect-beta
  api_id   = konnect_api.apis[each.key].id
  
  service = {
    control_plane_id = local.control_plane_id
    # This will reference the deck-generated service mapping
    id = local.deck_generated_services[each.value.service_name]
  }
  
  depends_on = [
    konnect_api_specification.specifications
  ]
}

# API Publications
resource "konnect_api_publication" "publications" {
  for_each = local.apis_config.apis
  
  provider                   = konnect-beta
  api_id                     = konnect_api.apis[each.key].id
  portal_id                  = local.portal_id
  visibility                 = each.value.publication.visibility
  auto_approve_registrations = each.value.publication.auto_approve_registrations
  
  depends_on = [
    konnect_api_implementation.implementations,
    konnect_api_document.documents
  ]
}
