#!/bin/bash

# Kong-Compliant Gateway Resources Generator
# Uses deck (Kong's official tool) to generate Kong resources from OpenAPI specs
# Then integrates them into Terraform configuration

set -e

SPECS_DIR="../specs"
CONFIG_DIR="../config"
TERRAFORM_DIR="../terraform"
GENERATED_DIR="./generated"
MAIN_TF_FILE="${TERRAFORM_DIR}/main.tf"

echo "🚀 Kong-Compliant ApiOps Resource Generation"
echo "=============================================="

# Validate prerequisites
if ! command -v deck &> /dev/null; then
    echo "❌ Error: deck CLI not found"
    echo "Install deck: https://docs.konghq.com/deck/latest/installation/"
    exit 1
fi

if ! command -v yq &> /dev/null; then
    echo "❌ Error: yq not found"
    echo "Install yq: https://github.com/mikefarah/yq#install"
    exit 1
fi

echo "✅ Prerequisites validated"

# Create generated directory
mkdir -p "$GENERATED_DIR"

# Load APIs configuration
APIS_CONFIG_FILE="${CONFIG_DIR}/apis.yaml"
if [ ! -f "$APIS_CONFIG_FILE" ]; then
    echo "❌ Error: APIs configuration not found at $APIS_CONFIG_FILE"
    exit 1
fi

echo "✅ Found APIs configuration"

# Process each OpenAPI specification
ALL_GATEWAY_RESOURCES=""
SERVICE_MAPPING=""

for spec_file in "${SPECS_DIR}"/*.yaml; do
    if [ ! -f "$spec_file" ]; then
        continue
    fi
    
    spec_filename=$(basename "$spec_file")
    spec_name="${spec_filename%.*}"
    
    echo ""
    echo "🔄 Processing OpenAPI spec: $spec_filename"
    
    # Extract Kong service name from OpenAPI spec
    KONG_SERVICE_NAME=$(yq eval '.x-kong-name // "not-found"' "$spec_file")
    if [ "$KONG_SERVICE_NAME" = "not-found" ]; then
        echo "⚠️  Warning: No x-kong-name found in $spec_filename, using filename"
        KONG_SERVICE_NAME="$spec_name"
    fi
    
    echo "   Service name: $KONG_SERVICE_NAME"
    
    # Step 1: Generate Kong declarative config using deck (Kong's official tool)
    echo "   📋 Generating Kong declarative config..."
    kong_config_file="${GENERATED_DIR}/${spec_name}-kong.yaml"
    
    cd "$(dirname "$spec_file")" || exit 1
    #deck file openapi2kong --file "$spec_filename" --output-file "../scripts/${kong_config_file}"
    cat "$spec_filename" | deck file openapi2kong > "../scripts/${kong_config_file}"
    cd - > /dev/null || exit 1
    
    if [ $? -eq 0 ]; then
        echo "   ✅ Generated Kong config: $kong_config_file"
    else
        echo "   ❌ Failed to generate Kong config for $spec_filename"
        continue
    fi
    
    # Step 2: Generate Terraform from Kong declarative config using deck
    echo "   🏗️  Generating Terraform resources..."
    terraform_file="${GENERATED_DIR}/${spec_name}-terraform.tf"
    
    #deck file kong2tf --file "$kong_config_file" --output-file "$terraform_file"
    cat "$kong_config_file" | deck file kong2tf > "$terraform_file"


    if [ $? -eq 0 ]; then
        echo "   ✅ Generated Terraform: $terraform_file"
    else
        echo "   ❌ Failed to generate Terraform for $spec_filename"
        continue
    fi
    
    # Step 3: Process the generated Terraform
    echo "   🔧 Processing Terraform resources..."
    
    # Update variable references to use local values
    sed -i.bak 's/var\.control_plane_id/local.control_plane_id/g' "$terraform_file"
    
    # Create unique resource names by prefixing with service name
    terraform_service_name=$(echo "$KONG_SERVICE_NAME" | sed 's/-/_/g')
    
    # Read the processed Terraform content
    terraform_content=$(cat "$terraform_file")
    
    # Clean up backup files
    rm -f "${terraform_file}.bak"*
    
    # Append to all gateway resources
    ALL_GATEWAY_RESOURCES="${ALL_GATEWAY_RESOURCES}

# ===================================================================
# GATEWAY RESOURCES FOR: $spec_filename ($KONG_SERVICE_NAME)
# Generated by deck from OpenAPI specification
# ===================================================================

${terraform_content}
"
    
    # Build service mapping for API implementations
    SERVICE_MAPPING="${SERVICE_MAPPING}
    \"$KONG_SERVICE_NAME\" = konnect_gateway_service.${terraform_service_name}.id"
    
    echo "   ✅ Processed Terraform resources"
done

# Generate the service mapping resource
SERVICE_MAP_RESOURCE="
# Service mapping for API implementations
locals {
  deck_generated_services = {$SERVICE_MAPPING
  }
}"

# Step 4: Update main.tf with generated resources
echo ""
echo "🔧 Integrating gateway resources into main.tf..."

# Create backup
cp "$MAIN_TF_FILE" "${MAIN_TF_FILE}.backup"

# Find and replace the gateway resources section
START_MARKER="# IMPORT DECK-GENERATED TERRAFORM RESOURCES"
END_MARKER="# PORTAL RESOURCES"

# Create temporary file with updated content
{
    # Copy everything before the start marker
    sed "/$START_MARKER/q" "$MAIN_TF_FILE"
    
    # Add the service mapping
    echo "$SERVICE_MAP_RESOURCE"
    
    # Add all generated gateway resources
    echo "$ALL_GATEWAY_RESOURCES"
    
    # Add everything after the end marker
    sed -n "/$END_MARKER/,\$p" "$MAIN_TF_FILE"
} > "${MAIN_TF_FILE}.tmp"

# Replace the original file
mv "${MAIN_TF_FILE}.tmp" "$MAIN_TF_FILE"

echo "✅ Updated main.tf with deck-generated resources"

# Step 5: Update API implementation service references
echo "🔧 Updating API implementation service references..."

# Replace the placeholder service reference with actual mapping
sed -i.bak 's/local\.deck_generated_services\[each\.value\.service_name\]/local.deck_generated_services[each.value.service_name]/g' "$MAIN_TF_FILE"

rm -f "${MAIN_TF_FILE}.bak"

echo "✅ Updated service references"

echo ""
echo "🎉 Kong-Compliant Resource Generation Complete!"
echo "==============================================="
echo "✅ Used deck for OpenAPI → Kong config conversion"
echo "✅ Used deck for Kong config → Terraform conversion"
echo "✅ Integrated deck-generated resources into Terraform"
echo "✅ Updated service references for API implementations"
echo ""
echo "🔧 Next steps:"
echo "1. cd ../terraform"
echo "2. terraform init"
echo "3. terraform plan"
echo "4. terraform apply"
